package com.oceanview.model;

import java.time.LocalDateTime;

/**
 * Entity class representing a billing invoice at Ocean View Resort.
 * 
 * <p>Maps to the 'bills' table in oceanview_resort_db.</p>
 * 
 * <p><b>Requirement Traceability:</b> Maps to "Calculate and Print Bill"
 * feature - computes total stay cost based on number of nights
 * and room rates.</p>
 * 
 * <p><b>Assumption:</b> Bill data is denormalized (guest name, room type
 * stored directly) to preserve a snapshot of billing details at the
 * time of invoice generation, even if the reservation is later modified.</p>
 * 
 * <p><b>Design Pattern:</b> Builder Pattern for flexible object creation.</p>
 * 
 * @author Dayani Samaraweera
 * @version 1.0
 */
public class InvoiceRecord {

    /** Unique bill identifier (auto-generated by database) */
    private int billId;

    /** System-generated bill number (format: BILL-YYYY-NNNNN) */
    private String billNumber;

    /** Foreign key reference to the reservation */
    private int reservationId;

    /** Reservation number stored for quick reference */
    private String reservationNumber;

    /** Guest name at the time of billing */
    private String guestName;

    /** Room type at the time of billing */
    private String roomType;

    /** Nightly rate at the time of billing (LKR) */
    private double ratePerNight;

    /** Total number of nights stayed */
    private int numberOfNights;

    /** Subtotal before tax: ratePerNight * numberOfNights */
    private double subtotal;

    /** Tax percentage applied (default 0%) */
    private double taxPercentage;

    /** Calculated tax amount */
    private double taxAmount;

    /** Final total: subtotal + taxAmount */
    private double totalAmount;

    /** Foreign key reference to the user who generated this bill */
    private int generatedBy;

    /** Timestamp when the bill was generated */
    private LocalDateTime generatedAt;

    // ========== Display field populated from JOIN ==========

    /** Name of the user who generated the bill (from JOIN) */
    private String generatedByName;

    /**
     * Default no-argument constructor.
     */
    public InvoiceRecord() {
    }

    /**
     * Private constructor used exclusively by the Builder.
     *
     * @param builder the Builder instance containing field values
     */
    private InvoiceRecord(Builder builder) {
        this.billId = builder.billId;
        this.billNumber = builder.billNumber;
        this.reservationId = builder.reservationId;
        this.reservationNumber = builder.reservationNumber;
        this.guestName = builder.guestName;
        this.roomType = builder.roomType;
        this.ratePerNight = builder.ratePerNight;
        this.numberOfNights = builder.numberOfNights;
        this.subtotal = builder.subtotal;
        this.taxPercentage = builder.taxPercentage;
        this.taxAmount = builder.taxAmount;
        this.totalAmount = builder.totalAmount;
        this.generatedBy = builder.generatedBy;
        this.generatedAt = builder.generatedAt;
        this.generatedByName = builder.generatedByName;
    }

    // ======================== GETTERS ========================

    /** @return the unique bill identifier */
    public int getBillId() { return billId; }

    /** @return the system-generated bill number */
    public String getBillNumber() { return billNumber; }

    /** @return the linked reservation ID */
    public int getReservationId() { return reservationId; }

    /** @return the linked reservation number */
    public String getReservationNumber() { return reservationNumber; }

    /** @return the guest name on the bill */
    public String getGuestName() { return guestName; }

    /** @return the room type on the bill */
    public String getRoomType() { return roomType; }

    /** @return the nightly rate on the bill */
    public double getRatePerNight() { return ratePerNight; }

    /** @return the number of nights on the bill */
    public int getNumberOfNights() { return numberOfNights; }

    /** @return the subtotal before tax */
    public double getSubtotal() { return subtotal; }

    /** @return the tax percentage */
    public double getTaxPercentage() { return taxPercentage; }

    /** @return the tax amount */
    public double getTaxAmount() { return taxAmount; }

    /** @return the final total amount */
    public double getTotalAmount() { return totalAmount; }

    /** @return the generator's user ID */
    public int getGeneratedBy() { return generatedBy; }

    /** @return the generation timestamp */
    public LocalDateTime getGeneratedAt() { return generatedAt; }

    /** @return the generator's full name (from JOIN) */
    public String getGeneratedByName() { return generatedByName; }

    // ======================== SETTERS ========================

    /** @param billId the bill identifier to set */
    public void setBillId(int billId) { this.billId = billId; }

    /** @param billNumber the bill number to set */
    public void setBillNumber(String billNumber) { this.billNumber = billNumber; }

    /** @param reservationId the reservation ID to set */
    public void setReservationId(int reservationId) { this.reservationId = reservationId; }

    /** @param reservationNumber the reservation number to set */
    public void setReservationNumber(String reservationNumber) { this.reservationNumber = reservationNumber; }

    /** @param guestName the guest name to set */
    public void setGuestName(String guestName) { this.guestName = guestName; }

    /** @param roomType the room type to set */
    public void setRoomType(String roomType) { this.roomType = roomType; }

    /** @param ratePerNight the nightly rate to set */
    public void setRatePerNight(double ratePerNight) { this.ratePerNight = ratePerNight; }

    /** @param numberOfNights the number of nights to set */
    public void setNumberOfNights(int numberOfNights) { this.numberOfNights = numberOfNights; }

    /** @param subtotal the subtotal to set */
    public void setSubtotal(double subtotal) { this.subtotal = subtotal; }

    /** @param taxPercentage the tax percentage to set */
    public void setTaxPercentage(double taxPercentage) { this.taxPercentage = taxPercentage; }

    /** @param taxAmount the tax amount to set */
    public void setTaxAmount(double taxAmount) { this.taxAmount = taxAmount; }

    /** @param totalAmount the total amount to set */
    public void setTotalAmount(double totalAmount) { this.totalAmount = totalAmount; }

    /** @param generatedBy the generator's user ID to set */
    public void setGeneratedBy(int generatedBy) { this.generatedBy = generatedBy; }

    /** @param generatedAt the generation timestamp to set */
    public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }

    /** @param generatedByName the generator name to set (display field) */
    public void setGeneratedByName(String generatedByName) { this.generatedByName = generatedByName; }

    @Override
    public String toString() {
        return "InvoiceRecord{billId=" + billId
                + ", billNumber='" + billNumber + "'"
                + ", reservationNumber='" + reservationNumber + "'"
                + ", guestName='" + guestName + "'"
                + ", totalAmount=" + totalAmount + "}";
    }

    // ======================== BUILDER ========================

    /**
     * Builder class for constructing InvoiceRecord instances.
     */
    public static class Builder {

        private int billId;
        private String billNumber;
        private int reservationId;
        private String reservationNumber;
        private String guestName;
        private String roomType;
        private double ratePerNight;
        private int numberOfNights;
        private double subtotal;
        private double taxPercentage = 0.00;
        private double taxAmount = 0.00;
        private double totalAmount;
        private int generatedBy;
        private LocalDateTime generatedAt;
        private String generatedByName;

        public Builder billId(int billId) { this.billId = billId; return this; }
        public Builder billNumber(String billNumber) { this.billNumber = billNumber; return this; }
        public Builder reservationId(int reservationId) { this.reservationId = reservationId; return this; }
        public Builder reservationNumber(String reservationNumber) { this.reservationNumber = reservationNumber; return this; }
        public Builder guestName(String guestName) { this.guestName = guestName; return this; }
        public Builder roomType(String roomType) { this.roomType = roomType; return this; }
        public Builder ratePerNight(double ratePerNight) { this.ratePerNight = ratePerNight; return this; }
        public Builder numberOfNights(int numberOfNights) { this.numberOfNights = numberOfNights; return this; }
        public Builder subtotal(double subtotal) { this.subtotal = subtotal; return this; }
        public Builder taxPercentage(double taxPercentage) { this.taxPercentage = taxPercentage; return this; }
        public Builder taxAmount(double taxAmount) { this.taxAmount = taxAmount; return this; }
        public Builder totalAmount(double totalAmount) { this.totalAmount = totalAmount; return this; }
        public Builder generatedBy(int generatedBy) { this.generatedBy = generatedBy; return this; }
        public Builder generatedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; return this; }
        public Builder generatedByName(String generatedByName) { this.generatedByName = generatedByName; return this; }

        /**
         * Constructs the InvoiceRecord instance.
         *
         * @return a new InvoiceRecord object
         */
        public InvoiceRecord build() {
            return new InvoiceRecord(this);
        }
    }
}