package com.oceanview.model;

import java.time.LocalDateTime;

/**
 * Entity class representing a hotel room at Ocean View Resort.
 * 
 * <p>Maps to the 'rooms' table in oceanview_resort_db.</p>
 * 
 * <p><b>Assumption:</b> Ocean View Resort has 14 rooms across 4 floors:
 * Floor 1 - Standard (LKR 5,500), Floor 2 - Superior (LKR 8,500),
 * Floor 3 - Premium (LKR 13,000), Floor 4 - Executive (LKR 22,000).</p>
 * 
 * <p><b>Design Pattern:</b> Builder Pattern for flexible object creation.</p>
 * 
 * @author Dayani Samaraweera
 * @version 1.0
 */
public class ResortRoom {

    /** Unique room identifier (auto-generated by database) */
    private int roomId;

    /** Physical room number displayed to guests (e.g., 101, 202) */
    private String roomNumber;

    /** Room type: Standard, Superior, Premium, or Executive */
    private String roomType;

    /** Nightly rate in LKR for this room type */
    private double ratePerNight;

    /** Availability flag: true = room can be booked */
    private boolean isAvailable;

    /** Floor number where the room is located (1-4) */
    private int floorNumber;

    /** Maximum number of guests allowed in this room */
    private int maxGuests;

    /** Brief description of room features and view */
    private String roomDescription;

    /** Timestamp when the room record was created */
    private LocalDateTime createdAt;

    /**
     * Default no-argument constructor.
     */
    public ResortRoom() {
    }

    /**
     * Private constructor used exclusively by the Builder.
     *
     * @param builder the Builder instance containing field values
     */
    private ResortRoom(Builder builder) {
        this.roomId = builder.roomId;
        this.roomNumber = builder.roomNumber;
        this.roomType = builder.roomType;
        this.ratePerNight = builder.ratePerNight;
        this.isAvailable = builder.isAvailable;
        this.floorNumber = builder.floorNumber;
        this.maxGuests = builder.maxGuests;
        this.roomDescription = builder.roomDescription;
        this.createdAt = builder.createdAt;
    }

    // ======================== GETTERS ========================

    /** @return the unique room identifier */
    public int getRoomId() { return roomId; }

    /** @return the physical room number */
    public String getRoomNumber() { return roomNumber; }

    /** @return the room type (Standard/Superior/Premium/Executive) */
    public String getRoomType() { return roomType; }

    /** @return the nightly rate in LKR */
    public double getRatePerNight() { return ratePerNight; }

    /** @return true if the room is available for booking */
    public boolean getIsAvailable() { return isAvailable; }

    /** @return the floor number */
    public int getFloorNumber() { return floorNumber; }

    /** @return the maximum number of guests */
    public int getMaxGuests() { return maxGuests; }

    /** @return the room description */
    public String getRoomDescription() { return roomDescription; }

    /** @return the record creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    // ======================== SETTERS ========================

    /** @param roomId the unique room identifier to set */
    public void setRoomId(int roomId) { this.roomId = roomId; }

    /** @param roomNumber the physical room number to set */
    public void setRoomNumber(String roomNumber) { this.roomNumber = roomNumber; }

    /** @param roomType the room type to set */
    public void setRoomType(String roomType) { this.roomType = roomType; }

    /** @param ratePerNight the nightly rate to set */
    public void setRatePerNight(double ratePerNight) { this.ratePerNight = ratePerNight; }

    /** @param isAvailable the availability status to set */
    public void setIsAvailable(boolean isAvailable) { this.isAvailable = isAvailable; }

    /** @param floorNumber the floor number to set */
    public void setFloorNumber(int floorNumber) { this.floorNumber = floorNumber; }

    /** @param maxGuests the maximum guest count to set */
    public void setMaxGuests(int maxGuests) { this.maxGuests = maxGuests; }

    /** @param roomDescription the description to set */
    public void setRoomDescription(String roomDescription) { this.roomDescription = roomDescription; }

    /** @param createdAt the creation timestamp to set */
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    @Override
    public String toString() {
        return "ResortRoom{roomId=" + roomId
                + ", roomNumber='" + roomNumber + "'"
                + ", roomType='" + roomType + "'"
                + ", ratePerNight=" + ratePerNight
                + ", isAvailable=" + isAvailable + "}";
    }

    // ======================== BUILDER ========================

    /**
     * Builder class for constructing ResortRoom instances.
     * 
     * <p>Usage example:</p>
     * <pre>
     * ResortRoom room = new ResortRoom.Builder()
     *     .roomNumber("101")
     *     .roomType("Standard")
     *     .ratePerNight(5500.00)
     *     .isAvailable(true)
     *     .floorNumber(1)
     *     .maxGuests(2)
     *     .build();
     * </pre>
     */
    public static class Builder {

        private int roomId;
        private String roomNumber;
        private String roomType;
        private double ratePerNight;
        private boolean isAvailable = true;
        private int floorNumber;
        private int maxGuests = 2;
        private String roomDescription;
        private LocalDateTime createdAt;

        public Builder roomId(int roomId) {
            this.roomId = roomId;
            return this;
        }

        public Builder roomNumber(String roomNumber) {
            this.roomNumber = roomNumber;
            return this;
        }

        public Builder roomType(String roomType) {
            this.roomType = roomType;
            return this;
        }

        public Builder ratePerNight(double ratePerNight) {
            this.ratePerNight = ratePerNight;
            return this;
        }

        public Builder isAvailable(boolean isAvailable) {
            this.isAvailable = isAvailable;
            return this;
        }

        public Builder floorNumber(int floorNumber) {
            this.floorNumber = floorNumber;
            return this;
        }

        public Builder maxGuests(int maxGuests) {
            this.maxGuests = maxGuests;
            return this;
        }

        public Builder roomDescription(String roomDescription) {
            this.roomDescription = roomDescription;
            return this;
        }

        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Constructs the ResortRoom instance.
         *
         * @return a new ResortRoom object
         */
        public ResortRoom build() {
            return new ResortRoom(this);
        }
    }
}