package com.oceanview.model;

import java.time.LocalDateTime;

/**
 * Entity class representing a system user at Ocean View Resort.
 * 
 * <p>Maps to the 'users' table in oceanview_resort_db.
 * Supports two roles: ADMIN (Resort Manager) and RECEPTIONIST (Staff).</p>
 * 
 * <p><b>Design Pattern:</b> Builder Pattern is used for flexible
 * object construction, allowing creation of SystemUser objects
 * with only the required fields.</p>
 * 
 * <p><b>Requirement Traceability:</b> Maps to "User Authentication (Login)"
 * feature - username and password_hash are used for secure login.</p>
 * 
 * <p><b>Password Change Flow:</b> When Admin creates a new staff account,
 * mustChangePassword is set to true. On first login, the staff member
 * is forced to change their temporary credentials before accessing
 * the dashboard.</p>
 * 
 * @author Dayani Samaraweera
 * @version 1.1
 */
public class SystemUser {

    /** Unique identifier for the user (auto-generated by database) */
    private int userId;

    /** Login username - must be unique across the system */
    private String username;

    /** SHA-256 hashed password for secure authentication */
    private String passwordHash;

    /** Full display name of the user */
    private String fullName;

    /** Role: ADMIN (full access) or RECEPTIONIST (limited access) */
    private String userRole;

    /** Email address for notifications (Observer pattern) */
    private String emailAddress;

    /** Active status flag: true = active, false = deactivated */
    private boolean isActive;

    /** 
     * Password change flag: true = user must change password on next login.
     * Set to true when Admin creates a new staff account with temporary
     * credentials. Reset to false after the staff member changes their password.
     */
    private boolean mustChangePassword;

    /** Timestamp when the user account was created */
    private LocalDateTime createdAt;

    /** Timestamp of the last account modification */
    private LocalDateTime updatedAt;

    /**
     * Default no-argument constructor.
     * Used when populating from database ResultSet.
     */
    public SystemUser() {
    }

    /**
     * Private constructor used exclusively by the Builder.
     * Ensures controlled object creation.
     *
     * @param builder the Builder instance containing field values
     */
    private SystemUser(Builder builder) {
        this.userId = builder.userId;
        this.username = builder.username;
        this.passwordHash = builder.passwordHash;
        this.fullName = builder.fullName;
        this.userRole = builder.userRole;
        this.emailAddress = builder.emailAddress;
        this.isActive = builder.isActive;
        this.mustChangePassword = builder.mustChangePassword;
        this.createdAt = builder.createdAt;
        this.updatedAt = builder.updatedAt;
    }

    // ======================== GETTERS ========================

    /** @return the unique user identifier */
    public int getUserId() { return userId; }

    /** @return the login username */
    public String getUsername() { return username; }

    /** @return the SHA-256 hashed password */
    public String getPasswordHash() { return passwordHash; }

    /** @return the full display name */
    public String getFullName() { return fullName; }

    /** @return the user role (ADMIN or RECEPTIONIST) */
    public String getUserRole() { return userRole; }

    /** @return the email address */
    public String getEmailAddress() { return emailAddress; }

    /** @return true if the account is active */
    public boolean getIsActive() { return isActive; }

    /** @return true if user must change password on next login */
    public boolean getMustChangePassword() { return mustChangePassword; }

    /** @return the account creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the last modification timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }

    // ======================== SETTERS ========================

    /** @param userId the unique user identifier to set */
    public void setUserId(int userId) { this.userId = userId; }

    /** @param username the login username to set */
    public void setUsername(String username) { this.username = username; }

    /** @param passwordHash the SHA-256 hashed password to set */
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }

    /** @param fullName the full display name to set */
    public void setFullName(String fullName) { this.fullName = fullName; }

    /** @param userRole the role to set (ADMIN or RECEPTIONIST) */
    public void setUserRole(String userRole) { this.userRole = userRole; }

    /** @param emailAddress the email address to set */
    public void setEmailAddress(String emailAddress) { this.emailAddress = emailAddress; }

    /** @param isActive the active status to set */
    public void setIsActive(boolean isActive) { this.isActive = isActive; }

    /** @param mustChangePassword the password change flag to set */
    public void setMustChangePassword(boolean mustChangePassword) { 
        this.mustChangePassword = mustChangePassword; 
    }

    /** @param createdAt the creation timestamp to set */
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    /** @param updatedAt the modification timestamp to set */
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }

    /** @return string representation for logging and debugging */
    @Override
    public String toString() {
        return "SystemUser{userId=" + userId
                + ", username='" + username + "'"
                + ", fullName='" + fullName + "'"
                + ", userRole='" + userRole + "'"
                + ", isActive=" + isActive
                + ", mustChangePassword=" + mustChangePassword + "}";
    }

    // ======================== BUILDER ========================

    /**
     * Builder class for constructing SystemUser instances.
     * 
     * <p><b>Design Pattern:</b> Builder Pattern (GoF) -
     * Separates the construction of a complex object from
     * its representation, allowing the same construction
     * process to create different representations.</p>
     * 
     * <p>Usage example:</p>
     * <pre>
     * SystemUser admin = new SystemUser.Builder()
     *     .username("admin")
     *     .passwordHash(PasswordHashGenerator.generateHash("admin123"))
     *     .fullName("Resort Manager")
     *     .userRole("ADMIN")
     *     .emailAddress("admin@oceanviewresort.lk")
     *     .isActive(true)
     *     .mustChangePassword(false)
     *     .build();
     * </pre>
     */
    public static class Builder {

        private int userId;
        private String username;
        private String passwordHash;
        private String fullName;
        private String userRole;
        private String emailAddress;
        private boolean isActive = true;
        private boolean mustChangePassword = false;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;

        public Builder userId(int userId) { this.userId = userId; return this; }
        public Builder username(String username) { this.username = username; return this; }
        public Builder passwordHash(String passwordHash) { this.passwordHash = passwordHash; return this; }
        public Builder fullName(String fullName) { this.fullName = fullName; return this; }
        public Builder userRole(String userRole) { this.userRole = userRole; return this; }
        public Builder emailAddress(String emailAddress) { this.emailAddress = emailAddress; return this; }
        public Builder isActive(boolean isActive) { this.isActive = isActive; return this; }
        public Builder mustChangePassword(boolean mustChangePassword) { 
            this.mustChangePassword = mustChangePassword; return this; 
        }
        public Builder createdAt(LocalDateTime createdAt) { this.createdAt = createdAt; return this; }
        public Builder updatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; return this; }

        /**
         * Constructs the SystemUser instance with the configured values.
         * @return a new SystemUser object
         */
        public SystemUser build() { return new SystemUser(this); }
    }
}